name: git hub sync

on: [pull_request]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_branch: "development"
        destination_branch: "feature/1"
        github_token: ${{ secrets.REPO_SYNC_TOKEN }}
